### ISSUE TITLE
New mini3 node (High Sierra): builds are slow

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#102]
mini3 (new machine on High Sierra) has been setup but is running builds slower than others. We've [encountered this behaviour](https://github.com/ros2/ros2/issues/409) when we upgraded Dosa to High Sierra but I was hoping it wouldn't happen on newer hardware.

First build mini3 ever did: https://ci.ros2.org/view/All/job/test_ci_osx/55: Testing starts at 2h44
Second build on mini3: https://ci.ros2.org/view/All/job/test_ci_osx/56: Testing starts at 1h59
Build on mini2 for comparison: https://ci.ros2.org/view/nightly/job/nightly_osx_release/797: Testing starts at 0h53

Testing takes about an hour in all cases, it's the build times that are different. Given that build no. 2 took less time than build no. 1 ccache looks to be being used fine.

Running another build I do see `MacOS error: -67062` from `taskgated`, as mentioned in https://github.com/ros2/ros2/issues/409#issuecomment-347376038, at least 3 times a second.

@nuclearsandwich I think I remember you mentioning that signed binaries might resolve this, but that we decided instead to enable SIP on dosa: is there a reference to that thread?

**Comment by nuclearsandwich** [comment]
> I think I remember you mentioning that signed binaries might resolve this

I was never able to come to any reliable conclusion when studying dosa's behavior with taskgated as the results seemed to change day by day with no known changes to configuration. All I was able to learn with certainty was that with SIP disabled, taskgated seems to produce a _lot_ of errors, more than with SIP enabled despite the fact that the same binaries (signed or otherwise) should be running with either SIP configuration. Disabling taskgated entirely for our High Sierra build machines was something discussed but never tested. 


> is there a reference to that thread?

Some of the late discussion is part of this [Slack conversation](https://osrf.slack.com/archives/C5UEHBHD2/p1512062199000199) although it doesn't seem that the conclusion is described there. I'll see what other notes from that time are in my journals and report what I can find of interest.

**Comment by clalancette** [comment]
I'm not sure that mini3 is meaningfully slower than mini1 and mini2.  Looking at the build times for the last few osx_debug nightlies:

| Machine | Build time | Link |
| ----------  | ------------- | ----- |
| mini3      |  03:01:34  | [1235](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1235/consoleFull) |
| mini2      |  02:24:24  | [1234](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1234/consoleFull) |
| mini2      |  03:04:48  | [1233](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1233/consoleFull) |
| mini1      |  02:52:36  | [1232](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1232/consoleFull) |
| mini2      |  03:01:09  | [1231](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1231/consoleFull) |
| mini1      |  02:51:03  | [1230](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1230/consoleFull) |
| mini1      |  02:51:55  | [1229](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1229/consoleFull) |
| mini1      |  02:52:10  | [1228](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1228/consoleFull) |
| mini1      |  02:55:06  | [1227](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1227/consoleFull) |
| mini2      |  03:09:00  | [1226](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1226/consoleFull) |

(unfortunately we only have the one build on mini3).  Given that it doesn't seem to be out of the norm for these builds, I'm inclined to close this.  @nuclearsandwich any opinions?

**Comment by clalancette** [comment]
I'm going to close this out.  If we find that mini3 is significantly different in the future, we can open it back up or make a new issue.
