### ISSUE TITLE
rviz tests failing on aarch64 linux repeated

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#144]
See: https://github.com/ros2/ci/pull/211#issuecomment-407580662

**Comment by clalancette** [comment]
This is still a problem: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/624

**Comment by dirk-thomas** [comment]
Since the upstream package has an issue tracking the problem (and I don't expect much change there in the near future) I created ros2/ci#262 to disable these tests in the nightly aarch64 repeated job. If that PR gets merged I will close this since ticket since the upstream issue should be sufficient to track the problem.

**Comment by dirk-thomas** [comment]
Addressed during #168.
