### ISSUE TITLE
configure eatable as windows 10 machine

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#17]
see [discussion](https://github.com/ros2/ros2/issues/334) about dropping support for windows 8.1 and focusing on Windows 10

**Comment by nuclearsandwich** [comment]
If all eatable needs is a reimage to Windows 10 and then configuration as a buildfarm machine, I think I'll take this on while I'm in town next month.

**Comment by nuclearsandwich** [comment]
I am getting back to CA for Thanksgiving and so I'm gonna make this happen the first Friday I'm back (17 Nov).

**Comment by nuclearsandwich** [comment]
Since Dosa was the more critical machine to get back online, I spent a couple days working on it and the SIP issue (https://github.com/ros2/ros2/issues/409) so this didn't happen. I'll be back out to California over the holidays in 3 weeks and will go for eatable then.

**Comment by nuclearsandwich** [comment]
Eatable is back online running Windows 10. I didn't have time to configure it as a build machine and when I left there were some configuration issues that kept it inaccessible: namely, it defaulted to standby after 30 minutes idle (that's been resolved) and no multicast DNS was installed on it, which was resolved by installing the bonjour print services for Windows from Apple.

The outstanding work is to configure eatable for Jenkins work again.

Since we have a clean machine, is there anything special we want to try like installing only a VS2017 toolchain and not a VS2015 one? I'll cross-post this question to the internal mailing list for visibility.

**Comment by dirk-thomas** [comment]
If we want the machine to contribute "now" then it needs VS2015 to be installed since we can't build against Connext with VS2017 until the binaries become publically available. If we want to wait until that is the case and the we have flipped the switch to use VS2017 the machine could use just VS2017.

I don't expect any benefit from testing a VS2017-only installation at this time.

**Comment by nuclearsandwich** [comment]
Eatable is now Windows 10. At yesterday's ROS 2 meeting the team agreed that there wasn't an urgent need to bring it back online as a CI node so I'll use it to test config management for Windows CI nodes.

**Comment by mikaelarguedas** [comment]
Out of curiosity, did the disk get reformatted and repartitioned to address https://github.com/ros2/build_cop/issues/51 for when we start using it as a CI machine again ?

**Comment by nuclearsandwich** [comment]
> Out of curiosity, did the disk get reformatted and repartitioned to address #51 for when we start using it as a CI machine again ?

I'm pretty sure the larger drive is a separate physical drive. At least it appeared to be in the Windows partition manager during installation. Since the machine is fresh, we could reinstall windows on the larger drive instead. I didn't since I wasn't sure if the larger drive was a linux install or what (Windows gives no partition info beyond size).

**Comment by mikaelarguedas** [comment]
> I'm pretty sure the larger drive is a separate physical drive.

Thanks :+1: that was my original question in #51 that I never took time to answer :/

> I didn't since I wasn't sure if the larger drive was a linux install or what (Windows gives no partition info beyond size).

Sounds good, we can look into it when we reach the point where we want to recommission it.
