### ISSUE TITLE
Support building Crystal

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#221]
See: https://github.com/ros2/build_cop/issues/220#issuecomment-517063935

We need to verify that the next release of Crystal can be built on our current macOS and Windows machines (due to upgrades and specifically upgrading the OpenSplice version). And if not, we need to setup agents specifically for building Crystal again.

One option is to just change the version of OpenSplice being used, run the Crystal jobs, and then change the version back before adding it back to the pool. This can be done by just renaming a folder. On macOS I actually set it up as a symlink, so you just need to move the symlink to change the version being used.

**Comment by nuclearsandwich** [comment]
I have been working on Crystal support in CI in order to produce patch release 5.

Windows: works, but you have to remember to build with VS2017. Backporting https://github.com/ros2/rcl/pull/413 might make Crystal buildable with either VS version.

MacOS: TinyXML2 and Qt need to be downgraded currently to 6.2.0 and 5.12 respectively. Backporting https://github.com/ros2/rviz/pull/435 might fix the Qt issue. I'm not sure that the CMake changes needed for TinyXML2 7 are backport-able.

Linux: Our Docker images stopped working on Xenial due to some recent changes. I've fixed that with https://github.com/ros2/ci/pull/328

**Comment by nuclearsandwich** [comment]
Crystal support is no longer required now that Crystal has reached end-of-support has ended. We were building Crystal artifacts for platforms other than macOS until the final patch release.
