### ISSUE TITLE
Failure while building rviz_default_plugins on Windows Debug

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#237]
Example build: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_win_deb&build=1374)](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1374/)

First failure: https://ci.ros2.org/view/nightly/job/nightly_win_deb/1374/console#console-section-4

I suspect this is related to ros2/rviz#457. There has been another issue breaking Windows Debug builds until last night. However, build [#1371](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1371/) did build this code successfully before the other regression took out the build.

@jacobperron - the errors start in a generated interactive markers file - could you take a quick pass?

**Comment by jacobperron** [comment]
I can take a look :eyes:

**Comment by jacobperron** [comment]
Looks like it's because the state enum names are not sufficiently unique, colliding with Windows preprocessor defines (e.g. `DEBUG` and `ERROR`):

https://github.com/ros-visualization/interactive_markers/blob/2b682ab12f78a7efdee8c3085093a54a95855afe/include/interactive_markers/interactive_marker_client.hpp#L86-L89

I'll open a PR to address it.

**Comment by jacobperron** [comment]
See https://github.com/ros-visualization/interactive_markers/pull/49 (and it's connected PR) for a fix.
