### ISSUE TITLE
installing connext fails with timeout and ifconfig not found

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#26]
I was surprised by `/entry_point.sh: 20: /entry_point.sh: ifconfig: not found` which was in this job failure:

http://ci.ros2.org/view/nightly/job/nightly_linux_debug/469/console

I think it is just a timeout while installing or something. Perhaps this is a bug in the retry branch of the logic, but I don't know. I'll look into it tomorrow.

**Comment by clalancette** [comment]
FYI, I think that ifconfig error is a red herring.  That happens in every single job, for instance: http://ci.ros2.org/job/ci_linux-aarch64/205/consoleFull .  I think it ends up that newer Ubuntu doesn't install ifconfig by default, so that call always fails.

Whatever caused the above build to fail, I think it was something else.

**Comment by wjwwood** [comment]
Thanks @clalancette, either way we should sort it out, but I think you're right that something else was the cause.

**Comment by dhood** [comment]
this is the output from the [connext installation timing out](https://github.com/ros2/ci/commit/c8525bfea8dbfdc57cf230dd5fa40dbbf131f025#diff-b6a840578a8de476368251d416bc0b18R39). It looks like it had almost finished installing, so I'll make a PR to increase the timeout

**Comment by dhood** [comment]
https://github.com/ros2/ci/pull/78 will hopefully be enough to fix this.
