### ISSUE TITLE
Cross vendor tests between `rmw_cyclonedds_cpp` and `rmw_fastrtps_*` failing

### ISSUE THREAD

**Issue by ivanpauno** [ros2/build_farmer#268]
e.g.:
- https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/629/#showFailuresLink
- https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_extra_rmw_release/669/#showFailuresLink
- https://ci.ros2.org/view/nightly/job/nightly_osx_extra_rmw_release/681/#showFailuresLink

In Feb 19, the problem wasn't happening:
- https://ci.ros2.org/view/nightly/job/nightly_osx_extra_rmw_release/672/#showFailuresLink
- https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/614/#showFailuresLink
- https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_extra_rmw_release/637/

**Comment by ivanpauno** [comment]
CI up to `test_communication` `test_rclcpp`, with fastrtps pinned to v1.9.3:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9498)](http://ci.ros2.org/job/ci_linux/9498/)

**Comment by ivanpauno** [comment]
> CI up to `test_communication` `test_rclcpp`, with fastrtps pinned to v1.9.3:
> 
> * Linux [![Build Status](https://camo.githubusercontent.com/3d01d13a1cacfb0e27de5bec42822f3b2436b98f/687474703a2f2f63692e726f73322e6f72672f6275696c645374617475732f69636f6e3f6a6f623d63695f6c696e7578266275696c643d39343938)](http://ci.ros2.org/job/ci_linux/9498/)

It seems that we have the same problem with fastrtps pinned to v1.9.3.
Trying with cyclonedds pinned before 18feb:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9515)](http://ci.ros2.org/job/ci_linux/9515/)

**Comment by ivanpauno** [comment]
Checking if https://github.com/ros2/rmw_cyclonedds/pull/102 is the culprit, I'm running out of ideas:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9520)](http://ci.ros2.org/job/ci_linux/9520/)

**Comment by ivanpauno** [comment]
Ok, I did some tests locally, I figured out there are two groups of failures:
- One that can't be reproduced when using `Fast-RTPS` 1.9.3.
- I haven't still found why the others started failing.

An example of the first group is:
https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/629/testReport/junit/(root)/projectroot/test_node_name__rmw_fastrtps_cpp__rmw_cyclonedds_cpp/

The following output is shown in that test:
```
[node_name_list-2] 1583089612.646461 [108] dq.builtin: plist(vendor 1.15): parameter length 42 mod 4 != 0
```

And it seems to be comming from here: https://github.com/eclipse-cyclonedds/cyclonedds/blob/b84eee5abbd4e935d3e47186e07ed93e4730b5f1/src/core/ddsi/src/ddsi_plist.c#L2632.

@miguelcompany @richiware That error seems to be a regression introduce in some of the latest `v1.9.x` changes (haven't checked in what commit), could you check?

**Comment by ivanpauno** [comment]
I finally find the root cause of the other group of tests failing.
This group is composed by all `test_communication` tests failing, e.g.: https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/629/testReport/junit/test_communication/TestPublisherSubscriber/test_subscriber_terminates_in_a_finite_amount_of_time_BoundedSequences_/.
It has actually two root cases:

- It never works with current `Fast-RTPS` 1.9.x and any cyclonedds commit after 18feb. It fails because of the same reason that applies to the other group of tests.
- With `Fast-RTPS` pinned to `1.9.3`, I found that the regression was introduced in https://github.com/eclipse-cyclonedds/cyclonedds/commit/754eb4090eab64889215a119501f4e560c66bad7. If I also pin cyclonedds to af3604dea72b79d88eb477bd78eeb916efd05e97, all the test passes. @eboasson can you take a look?

It seems that regressions were introduced in both libraries almost simultaneously, so it was hard to me to find the root cause.

**Comment by rotu** [comment]
@ivanpauno, check out https://github.com/ros2/system_tests/pull/401. That should fix ~~at least~~ one contributing factor of the "test_subscriber_terminates..." bugs.

**Comment by MiguelCompany** [comment]
@ivanpauno I've found the issue on Fast-RTPS and I'm working on a fix.

**Comment by eboasson** [comment]
@rotu sent me a wireshark capture last night. It's from Dashing, but perfectly matches the symptoms and so, @MiguelCompany, you might want to have a look. It should be easy enough to determine whether Fast-RTPS has had any changes in this area.

From the capture (with a bit of background information for those reading it who are not familiar with the details of the protocol):

### Cyclone

* All packets originate from 10.0.0.8:35552

  Note that 35552 is just a random port number allocated by the kernel.  When multicast
  discovery is available, there's really no need for any predictable port numbers other
  than the one used for multicast discovery because all other addresses are discovered
  from there.

* The only address advertised by Cyclone is 10.0.0.8:35552.  The advertising happens in
  the "simple participant discovery protocol" messages, a.k.a. "SPDP", a.k.a. "DATA(p)" in
  the Wireshark summary.
  
  Advertising a set of addresses X1 .. Xn means informing the rest of the world that
  you're reachable on any of those addresses and that it is up to them to choose which
  subset to use.  A set of one, like here, simpy means no freedom of choice.

* The only multicasts it sends are SPDP ones to 17900, this is consistent with the "spdp"
  setting for AllowMulticast.  It learns of the existence of the Fast-RTPS node through
  multicast; from then on it uses the meta-traffic address advertised by Fast-RTPS
  (10.0.0.8:17912) to send its discovery data to it.

* All its packets (save for the very last) are, presumably, delivered by the kernel (there
  is no ICMP "destination unreachable" except for the last one).

### Fast-RTPS

* Sends from 10.0.0.8:55557 and 127.0.0.1:41837

  Note that implementations are free to pick any set of interfaces, and that Fast-RTPS is
  free to use two different interface simultaneously.  Both SPDP packets advertise
  10.0.0.8:17912 for meta-traffic and 10.0.0.8:17913 for data, therefore anyone trying to
  perform the next discovery steps must use 10.0.0.8:17912 because 127.0.0.1 one isn't
  advertised.
  
* It consistently sends to 127.0.0.1:35552 when trying to reach Cyclone, even though that
  address has never been advertised — that is (or was, if it has been changed since) a bug
  in Fast-RTPS.  All these result in ICMP "destination unreachable", as they should given that
  Cyclone bound its socket to 10.0.0.8.

Before the change @ivanpauno pinpointed (https://github.com/eclipse-cyclonedds/cyclonedds@754eb40) Cyclone bound its socket to0.0.0.0 and so these packets to  127.0.0.1:35552 would have been received and processed despite being addressed incorrectly. After that commit the socket is bound to 10.0.0.8 and these are dropped by the kernel because of an address mismatch.

[dashing-fail.pcapng.zip](https://github.com/ros2/build_farmer/files/4297249/dashing-fail.pcapng.zip)

**Comment by MiguelCompany** [comment]
> The following output is shown in that test:
> 
> ```
> [node_name_list-2] 1583089612.646461 [108] dq.builtin: plist(vendor 1.15): parameter length 42 mod 4 != 0
> ```

This should be fixed by eProsima/Fast-RTPS#1047

**Comment by ivanpauno** [comment]
> @rotu sent me a wireshark capture last night. It's from Dashing, but perfectly matches the symptoms and so, @MiguelCompany, you might want to have a look. It should be easy enough to determine whether Fast-RTPS has had any changes in this area.

As I commented [above](https://github.com/ros2/build_farmer/issues/268#issuecomment-595453565), the failing `test_communication` tests (e.g.: test_publisher_subscriber__rclpy__rmw_connext_cpp__rmw_cyclonedds_cpp) don't pass with Fast-RTPS pinned to v1.9.3, and it does pass when I pin cyclonedds to https://github.com/eclipse-cyclonedds/cyclonedds/commit/af3604dea72b79d88eb477bd78eeb916efd05e97 (i.e. failure introduced in https://github.com/eclipse-cyclonedds/cyclonedds/commit/754eb4090eab64889215a119501f4e560c66bad7).
`cyclonedds` was recently added to the default rmw implementations, and that triggered new connext<->cyclonedds cross vendor tests. The same tests can be seen to fail in the nightlies between cyclonedds and connext: https://ci.ros2.org/view/nightly/job/nightly_linux_release/1466/testReport/junit/(root)/projectroot/test_publisher_subscriber__rclcpp__rmw_connext_cpp__rmw_cyclonedds_cpp/.
If I pin cyclonedds locally to the commit mentioned previously, that test also start passing. Except a case testing with a `wstring` message, but that's an specific failure.

Considering that `cyclonedds` is failing again two different vendors, I bet a regression was introduced in https://github.com/eclipse-cyclonedds/cyclonedds/commit/754eb4090eab64889215a119501f4e560c66bad7. @eboasson can you check further?

**Comment by eboasson** [comment]
@ivanpauno it's a fact that Fast-RTPS in @rotu's trace (I presume it to be the version installed by Dashing) incorrectly addresses packets it intends to be received by Cyclone DDS: it uses a destination address that has never been advertised by Cyclone DDS. The change you pinpointed _exposes_ this bug in Fast-RTPS.

I agree that for the system it is a regression (it no longer works), but in terms of issues that need fixing, it isn't.

There is the possibility that this is something that is broken in Fast-RTPS @ Dashing and that has been fixed since. If so, there's something else going on in your test. Ideally, @MiguelCompany or someone else at eProsima would be able to confirm, saving a round of experimentation, collecting Wireshark traces, analysing them, &c.

The failure with RTI Connext I personally find more interesting. It could plausibly have the same cause, because Connext has a history of disregarding advertised addresses: over the years I have had many occasions where I had to tell projects that combined Connext and OpenSplice [*] to disable the Connext shared memory transport, and the only reason this was necessary was that Connext would assume that the shared memory transport could be used, without even checking whether the peer was an RTI implementation.

Now, I believe that particular bug got fixed eventually, and I wouldn't dare claim now that this interoperability issue with Connext is the same as what I found in @rotu's capture. For that, I would need evidence. I don't have access to Connext, but perhaps you can capture a Wireshark trace of that test? That would help tremendously.

[*] Cyclone's network stack is a derivative of OpenSplice's and is about a decade old now, with the scars of dealing with all kinds of quirks of others that (presumably) couldn't be changed. The interesting bit here is that the change you identified is recent and so the issue it exposes (other implementations not properly honouring the set of advertised addresses) would never have shown up in all the interoperability situations I have seen over that decade.

(Rant.) In between other implementations not honouring the protocol even at this fundamental level, and it being exposed because of a fix for Windows' quirk of not consistently routing multicast packets sent from sockets bound to 0.0.0.0 and with the correct outgoing interface selected when there are _also_ sockets sending multicasts to the same address that have been bound to an interface address, I'm getting a little upset with my fellow software builders. Clearly I can work around this nonsense, too, but I need a lot more convincing before I'll do that ... (End of rant.)

**Comment by dirk-thomas** [comment]
> I don't have access to Connext

@eboasson You can install the Debian package of Connext provided in the ROS apt repos: `rti-connext-dds-5.3.1`. That should allow you reproduce the problem.

**Comment by eboasson** [comment]
@dirk-thomas I'm afraid I can't, my employer has a policy not to touch anything from RTI (with the exception of their shapes demo in very limited settings) because of some nasty interactions over the years …

**Comment by eboasson** [comment]
(@dirk-thomas, if there's no other way, I could see if a friend of mine at RTI would have time to try ...)

**Comment by dirk-thomas** [comment]
@eboasson I understand you perspective. If neither of the two vendors which exhibit cross vendor communication problems wants to investigate the problem (in this case between Connext and CycloneDDS) there are two options:
* A third party (like Open Robotics) can take on the extra effort and debug the problem until it is clear which vendor should patch their side or
* Nobody debugs the problems and leaves the cross vendor communication in the state it is in.

In the past years Open Robotics has fulfilled this role many time. Moving forward I am not convinced it should do that anymore (just my personal opinion). If neither of the vendors wants to resolve the problem I am wondering why Open Robotics should do it for them?

**Comment by eboasson** [comment]
@dirk-thomas I totally agree it doesn’t make sense for OpenRobotics to do all the work. I’d be happy to investigate this if I know it won’t cause a problem. It seems to me there should not be any if RTI were to give me permission. Perhaps it would be possible for OpenRobotics to mediate and arrange for RTI to give an unambiguous statement that they’re fine with me doing this?

**Comment by dirk-thomas** [comment]
@neil-rti maybe you can help here.

**Comment by ivanpauno** [comment]
Though I like cross-vendors tests because it makes everybody to follow the standard better and it helps vendors to find regressions (at least, in the ones we build from source)(*), I think we should disable the failing tests until there is consensus about what is the problem (or who is not following the standard correctly).

* and I guess there aren't much projects running DDS cross-vendor tests daily

**Comment by dirk-thomas** [comment]
@ivanpauno Please see ros2/ros_buildfarm_config#78 which proposes to create separate cross-vendor jobs which only compare one specific pair at a time.That will allow us to parallelize the builds as well as easily ignore whichever combination doesn't work. Note this affects build.ros2.org / Linux only. For ci.ros2.org we can follow up after this has been deployed with the option of disabling the cross vendor tests.

**Comment by rotu** [comment]
Here's a capture of Connext -> Cyclone failing this test. Looks to me like the same syndrome. https://send.firefox.com/download/2e2f49a42ef3a753/#KWzx1u4ojbgrdEVTezsIKg

**Comment by eboasson** [comment]
Thanks @rotu! Yes, it is indeed the same phenomenon ...

And it intriguingly also shows Connext multicast pinging to port number 7400 (i.e., domain 0) in addition to port number 17900 (i.e., domain 42). Now I really understand why they proposed adding the domain id to the participant discovery data in DDSI 2.3.

**Comment by eboasson** [comment]
On reflection, the only thing a workaround in Cyclone really damages is my sense of fairness. Fast-RTPS can reasonably be expected to be upgraded by users running into this problem, but my experience with the commercial world is that upgrading can be a much more complicated affair. So, it ends up like:

* Do a work-around in Cyclone and no-one ever looks back. The bugs will probably remain, but no-one will notice;
* Insist that the bugs get fixed and it will take a long time before things generally work out-of-the-box for everyone. Until then, most likely, issues will get filed against Cyclone, and that will at best be a nuisance.

Therefore I'd better put a work-around in and cry myself to sleep.

It appears that a work-around is no more complicated than creating an additional socket for transmitting — like the others (probably) do — and bind this "transmit" socket to the IP address, while binding the "receive" sockets to 0.0.0.0.

That's what https://github.com/eclipse-cyclonedds/cyclonedds/pull/427 is supposed to do, but it'd be best to give it a try before committing it. Right now is not the time for me to try kicking off my first build ever on the ROS2 CI system, but if anyone feels like doing just that, that'd be great.

**Comment by ivanpauno** [comment]
> That's what eclipse-cyclonedds/cyclonedds#427 is supposed to do, but it'd be best to give it a try before committing it. Right now is not the time for me to try kicking off my first build ever on the ROS2 CI system, but if anyone feels like doing just that, that'd be great.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9571)](http://ci.ros2.org/job/ci_linux/9571/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9489)](http://ci.ros2.org/job/ci_windows/9489/)

**Comment by ivanpauno** [comment]
> * Do a work-around in Cyclone and no-one ever looks back. The bugs will probably remain, but no-one will notice;
> * Insist that the bugs get fixed and it will take a long time before things generally work out-of-the-box for everyone. Until then, most likely, issues will get filed against Cyclone, and that will at best be a nuisance.

I don't have an opinion about what to do.
Don't merging the workaround if you don't think it's correct is fine.
In that case, we can just disable the tests that are failing.
@dirk-thomas proposal for having separate cross-vendor jobs is good.

**Comment by eboasson** [comment]
> I don't have an opinion about what to do.
> Don't merging the workaround if you don't think it's correct is fine.

@ivanpauno I think the key thing is to do what helps the users and that is usually to make things work out-of-the-box. While I'm not too worried about Fast-RTPS in this context, I am concerned that without a work-around Cyclone DDS has less chance of gaining traction in, e.g., aerospace, because in that context it simply has to work with old versions of Connext, OpenSplice, Core DX, &c. So I really don't have much choice.

I am pretty sure I got it right, but given that we can check before merging it, doing a trial run makes more sense then potentially ending up with a sequence of commits trying to fix it.

> In that case, we can just disable the tests that are failing.

If I am right, they'll go green in the trial run. Then I'll merge it and the urgency of the problem will be gone :)

**Comment by eboasson** [comment]
@ivanpauno looks to me like it works. It's not quite green, but it is a rather greenish yellow, I'd say, because the WStrings issue between Connext and Cyclone has a different cause.

**Comment by ivanpauno** [comment]
> @ivanpauno looks to me like it works. It's not quite green, but it is a rather greenish yellow, I'd say, because the WStrings issue between Connext and Cyclone has a different cause.

Yes, looks greenish yellow to me too.

**Comment by MiguelCompany** [comment]
> Yes, looks greenish yellow to me too.

@ivanpauno The builds included eProsima/Fast-RTPS#1047, and I haven't seen cyclone complaining on `parameter length 42 mod 4 != 0` in the console output, so I guess the issue can be closed?

Now, regarding binding to 0.0.0.0 and transforming addresses to 127.0.0.1, this has been in Fast-RTPS for a very long time, and no interoperability issues have arisen till now.

Binding to 0.0.0.0 has the following advantages:
* When there are several network interfaces, only one listening socket is created, thus improving resource usage. The only disadvantage is that the socket buffer can get overflowed with data from all the interfaces, but those buffers can be increased.
* In the case of a network address change, there is no need to close and reopen the listening sockets. We can just update the announced addresses.

Transforming local addresses to 127.0.0.1 has the following advantages:
* When the same port is used, all addresses will be coalesced into a single one, so data will be sent only once.
* If something happens to the network interface and it loses its address (cable unplugged, wifi-disconnection, etc), localhost traffic will still work.

Those are the reasons why we are doing both things, and I suppose Connext reasons will be similiar.

I've taken note to add a flag on the configuration to disable the transformation to 127.0.0.1, as on some scenarios (when not using DHCP, for instance), it may be useful.

**Comment by ivanpauno** [comment]
CI looks pretty much green today!
Thanks @eboasson @MiguelCompany for your responses and fixes, and thanks @rotu for investigating the issue.

**Comment by dirk-thomas** [comment]
> the WStrings issue between Connext and Cyclone has a different cause.

@eboasson There are already two exceptions for testing `WStrings`: https://github.com/ros2/system_tests/blob/68c495a58df2502c77ebc972aba87c73ac46adcc/test_communication/CMakeLists.txt#L198-L216

Does the current test failure fall into the category "known issue, not likely to be resolved"? Then I would suggest we skip this specific combination / suppress the test failure. Or can it be fixed on CycloneDDS side - then I would keep the test enabled to make it pass with an upcoming PR.

**Comment by joespeed** [comment]
@dirk-thomas easily fixed in cyclonedds and want to ASAP. When we do, FastRTPS WStrings interop will fail until FastRTPS makes a fix, it has same defect.

**Comment by dirk-thomas** [comment]
@joespeed thanks for the feedback. Looking forward for the PR then.

@MiguelCompany FYI

**Comment by rotu** [comment]
@dirk-thomas why does that existing test suppression exist? It seems to be clear defect and the test between FastRTPS and Connext *should* be failing.

**Comment by dirk-thomas** [comment]
> why does that existing test suppression exist? It seems to be clear defect and the test between FastRTPS and Connext should be failing.

Both vendors implement different versions of the spec as far as I remember so they are not interoperable by design. I think Connext needs to catch up here.

**Comment by rotu** [comment]
I assumed that Connext did it right, because Cyclone DDS’s WString violates every version of the spec. And FastRTPS works with Cyclone, so it must also violate the spec.

**Comment by dirk-thomas** [comment]
Maybe the combination WStrings between Connext and CycloneDDS should just be skipped for the same reason as for Connext <-> FastRTPS? I will just leave it to you guys to decide what is right for CycloneDDS.

**Comment by eboasson** [comment]
The serialiser we use is part of the RMW layer (Cyclone DDS "proper" doesn't even do wstrings yet) and so for this particular matter, I think we should do what works best for ROS2.

Common sense says that "best" ought to be that everyone implements the current version of the spec and interoperates nicely, but that depends on a lot of players. Another reasonable interpretation of it is that it is more important to be compatible with the default RMW layer than to be compliant with the spec. No doubt that'll still eventually result in moving to the latest version of the spec, but it might mean doing so at a later stage.

**Comment by MiguelCompany** [comment]
> The serialiser we use is part of the RMW layer

This is also the case with `rmw_fastrtps`, but it depends on Fast CDR to perform the serialization of the `wstring`. This means we could think of a workaround on the rmw layer, such as serializing a sequence of uint32_t/uint16_t. This will at least work for the interoperability of the ROS2 topics, but may break pure DDS <-> ROS2 communications
