### ISSUE TITLE
packaging_linux{-aarch64} jobs failed dynamic_bridge tests

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#34]
http://ci.ros2.org/view/packaging/job/packaging_linux/717/
http://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/82/

The relevant output seems to be:

```
(test_dynamic_bridge_msg_1to2__roscore) pid 36139: ['/opt/ros/kinetic/env.sh', '/opt/ros/kinetic/bin/roscore'] (stderr > stdout, all > console)
(test_dynamic_bridge_msg_1to2__dynamic_bridge) pid 36141: ['/opt/ros/kinetic/env.sh', '/home/rosbuild/ci_scripts/ws/install/bin/dynamic_bridge'] (stderr > stdout, all > console)
(test_dynamic_bridge_msg_1to2__ros1talker) pid 36144: ['/opt/ros/kinetic/env.sh', 'rosrun', 'roscpp_tutorials', 'talker'] (stderr > stdout, all > console)
(test_dynamic_bridge_msg_1to2__ros2listener) Failed to spawn command ['listener']: [Errno 2] No such file or directory: 'listener'
```

Similarly, it couldn't find `talker` to launch either.

**Comment by mikaelarguedas** [comment]
Please provide link to relevant PRs rather than just copying console output: https://github.com/ros2/demos/pull/136 moved the executable in lib/<PACKAGE_NAME> so it's not on the path anymore. @dirk-thomas FYI this launchfile should be updated to use the new api once https://github.com/ros2/ros2cli/pull/12 is merged
