### ISSUE TITLE
packet machine crash on "resource busy"

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#42]
When running several jobs in parallel on the packet machine sometimes docker crashes throwing
"device or resource busy" or "mkdir /var/run/docker/libcontainerd/containerd/<HASH>: file exists"

examples:
http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/127
http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/112
http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/109

@nuclearsandwich FYI

**Comment by nuclearsandwich** [comment]
Thanks for the head's up. This machine uses the Xenial Docker package rather than the package I built for the ROS 2 buildfarm based on the 17.5 or 17.6 release (I don't have it in front of me at the moment).

Have you found an upstream Docker issue that matches this failure? Could be that it's a bug fixed between now and the one-off package we built.

**Comment by mikaelarguedas** [comment]
TBH I didn't look into it, I just dumped links here for book-keeping :S

**Comment by nuclearsandwich** [comment]
We haven't (to my knowledge) seen this in quite some time and I don't have any specific leads to follow it up with. Can we close it and revisit it if it pops up again?

**Comment by dirk-thomas** [comment]
> Can we close it and revisit it if it pops up again?

Sounds good to me.
