### ISSUE TITLE
Update java on Windows and Mac OS machines

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#43]
Java8u144 is available and updates pop-ups show up on most machines. Looks like some windows ones updated automatically. We should update a few, test and if all goes well update the remaining ones

**Comment by wjwwood** [comment]
I've installed Java8u144 on all the macOS machines. I don't think I'll do the Windows machines right now, but at least we got some progress on this issue.

**Comment by dhood** [comment]
all osx machines have java 8 update 151 now

**Comment by clalancette** [comment]
I'm updating Java on the Windows machines.  Here are the machines to update:

- [x] icecube
- [x] portable
- [x] windshield

(note that eatable is not in the list, since it needs a reinstall of Windows 10).  In order to successfully do the upgrade, I had to:

1.  Stop the Jenkins service
1.  Ensure that we are using the 64-bit version of Java, not the 32-bit version.  Check `C:\J\jenkins-slave.xml`, if the `<executable>` is pointing at `C:\Program Files (x86)\Java\...`, then it is using 32-bit.  In that case, uninstall the 32-bit version and install the 64-bit version instead.
1.  Do the Java update itself
1.  Open a cmd prompt as administrator
1.  cd \J
1.  jenkins-slave.exe uninstall
1.  jenkins-slave.exe install
1.  Reboot

**Comment by clalancette** [comment]
This is done now, so I'll close out the ticket.
