### ISSUE TITLE
test_communication took six hours on MacOS

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#5]
This [ci_osx job](http://ci.ros2.org/view/nightly/job/ci_osx/1909/) had been running for more than six hours when I came to check on builds this morning. I haven't yet killed it, because I want to know what other tests have missing or malfunctioning timeouts.

It doesn't appear that the job ever locked up. Instead it spent just over six hours on the [Test: test_communication](http://ci.ros2.org/view/nightly/job/ci_osx/1909/consoleFull#console-section-265) step. I have not yet determined if this is due to a misconfigured timeout or a missing timeout or something else entirely.

Earlier tests also appear to have failed but I have not yet dove into that either.

**Comment by mikaelarguedas** [comment]
I think the individual test timeouts are working as expected at the first glance. The problem seems to be that almost every test failed and has been repeated 10 times. That gives you something like (just taking the last pub sub failing tests): 130 failing tests * 15 seconds timeout * 10 retries ~ 5.5hours. That doesnt include the service tests that have a 30second timeout. So I think it's pretty close to what should be expected if most tests fail.

I think the main bottleneck here is that we have to retry 10 times to eliminate flaky tests (and that this job is runnign from a branch where DDS communication is broken)

**Comment by Karsten1987** [comment]
That was my individual build, trying to see if my namespace_impl. I let it
run on purpose to see if it would ever finish or simply collapse at one
point.

**Comment by nuclearsandwich** [comment]
> That was my individual build, trying to see if my namespace_impl. I let it run on purpose to see if it would ever finish or simply collapse at one point.

Got it.
