### ISSUE TITLE
detect CMake warnings without a filename:linenumber

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#73]
Right now we don't get all cmake warnings reported on CI.
Sometimes it's convenient (e.g. "Manually-specified variables were not used by the project:" as we pass the same cmake args to all packages).
But sometimes it's warnings we should address:
```
This is not defined behavior unless XXX is set to NEW.  For
compatibility with older versions of CMake, the previous undefined behavior
will be used.
```

**Comment by nuclearsandwich** [comment]
CMake warnings are parsed via an in-house regexp and script using the [Jenkins Warnings parser plugin](https://plugins.jenkins.io/warnings). Search for "Compiler warnings" on http://ci.ros2.org/configure (link requires authorization) for the regexp and the script to handle them. The one in CI is based on [the one ROS buildfarm uses](https://github.com/ros-infrastructure/buildfarm_deployment/blob/master/modules/jenkins_files/files/var/lib/jenkins/hudson.plugins.warnings.WarningsPublisher.xml) and may be identical currently. Because there is no config management for CI, we don't have any external versioning on the warnings config beyond the Jenkins config history so exercise caution when experimenting. You may want to add a `CMake - Testing` parser and change a ci config to use that instead in order to refine without affecting other jobs.

**Comment by mikaelarguedas** [comment]
Thanks for the information!
I won't work on this before the release but all this is very valuable information for the person that'll look into this issue in the future.

**Comment by dirk-thomas** [comment]
The currently used regular expression is only matching CMake messages which do have a filename:linenumber. Therefore I updated the title accordingly.

This should be addressed by ros-infrastructure/buildfarm_deployment#169 which has been deployed on ci.ros2.org.

**Comment by dirk-thomas** [comment]
I created two follow up PR to address some warnings which appeared in the CI builds:
* ros/console_bridge#50
* ros2/urdfdom#7
