### ISSUE TITLE
Coverage job failing since Dec 8 2017

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#76]
I'm not sure I'll have time to investigate further before the handoff so I'm logging this here.

The coverage job has been failing for 4 nights throwing a `java.lang.NullPointerException` at warning parsing time: http://ci.ros2.org/view/nightly/job/nightly_linux_coverage/599/

I cloned the job to investigate and the cloned job passed with the default parameters... http://ci.ros2.org/job/test_linux_coverage/6/

**Comment by dirk-thomas** [comment]
After looking into this I think the problem is related to the history of the job. A newly created job with the same config but without history works fine. Therefore I have recreated the job.

Even though I don't think that it is needed I have renamed the original job to keep the history accessible: http://ci.ros2.org/view/nightly/job/nightly_linux_coverage_backup/
