### ISSUE TITLE
flake8 started failing between Mar 17 and Mar 19 2018

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#99]
All jobs show flake8 failures as of this morning, e.g.: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/774/

Not sure when it broke as nightlies were broken over the weekend.

cc @dhood as build_cop

**Comment by dhood** [comment]
Python dependency changes over the weekend: https://www.diffchecker.com/n8oVIXWn

Regression from this PR in flake8-builtins; https://github.com/gforcada/flake8-builtins/commit/7580be71cccdb709a92447e97656da14d816866e#diff-fef87cfd8dd8ac2667a6ba1e5a368dc1R129

Issue already reported at: https://github.com/gforcada/flake8-builtins/issues/19

Will look at pinning to older version to avoid failures while it's being addressed upstream.

**Comment by dhood** [comment]
This was only failing on some files not all; for us, a file/files in `rclpy` and a file/files in `rosidl_parser`. In the upstream issue, pulling out tuples in a for loop was listed as one of the causes. We have that at https://github.com/ros2/rosidl/blob/774a3cd4509f2d432b7325f60434765a9ccd5cee/rosidl_parser/test/test_parse_primitive_value_string.py#L63 and at https://github.com/ros2/rclpy/blob/7180fdf4769230c93d919702fb853803bbefa43b/rclpy/rclpy/executors.py#L373

Since this isn't code that we want to change, we have pinned in https://github.com/ros2/ci/pull/129 and will revert when the regression is addressed upstream

**Comment by dhood** [comment]
unpinned because resolved upstream
